# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d25325ebaa928e417e92b54e10b95b82a73d23a156f1becc8ebaab942f308b304e397e1594f06e0e0070755580c39e84f27dfe5e72b4e6cfb8a28b87a23eece

test:
  secret_key_base: 7d60769e057796fd6165410ed6b7ae74f8b4f4b276eb70deb7443e93b024cca5dd3fc9b23a3edffd96725cb6c47bfdd850b5213e9efd6971aca8587dcca5342d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
